config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  resources :projects
  resources :contacts, only: [:new, :create]
  get 'welcome/index'
  root 'welcome#index'

  get '*path' => redirect('/')
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,     :validate => true
  attribute :email,    :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,  :validate => true
  attribute :nickname, :captcha  => true

  def headers
    {
      :subject => "Contact Form",
      :to => "ollie.p.carter@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  # use :registerable to add registration
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request =  request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all.order("created_at desc").paginate(page: params[:page], per_page: 10)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new post_params

    if @post.save
      redirect_to @post, notice: "Congratulations on your new article mah boi."
    else
      render 'new', notice: "Oh no, it didn't save."
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update post_params
      redirect_to @post, notice: "WooHoo, another article successfully saved!"
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :slug)
  end

  def find_post
    @post = Post.friendly.find(params[:id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :find_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @projects = Project.all.order("created_at desc")
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new project_params

    if @project.save
      redirect_to @project, notice: "Good job, you saved yourself a project!"
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @project.update project_params
      redirect_to @project, notice: "Good job, you updated yourself a project!"
    else
      render 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private

  def find_project
    @project = Project.friendly.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title, :description, :link, :slug)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = Post.all.limit(4).order("created_at desc")
    @projects = Project.all.limit(4).order("created_at desc")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end
  def markdown(content)
    renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      disable_indented_code_blocks: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true,
      tables: true
    }
    Redcarpet::Markdown.new(renderer, options).render(content).html_safe
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<div id="contacts-container">
  <div id="contacts-wrapper">
    <h1 id="page-title">You've contacted me!</h1>
    <h2>Thank you for the message :3</h2>
    <p>I'll make sure to get back to you soon!</p>
    <p>Click the O | C link in the top right to go home for more content :D</p>
  </div>
</div>

app/views/contacts/new.html.erb
<div id="contacts-container">
  <div id="contacts-wrapper">
    <h1 id="page-title">Need to contact me?</h1>
    <%= form_for @contact do |f| %>
      <div class="label">
        <%= f.label :name %><br>
      </div>
      <%= f.text_field :name, required: true %>

      <br>
      <br>


      <div class="label">
        <%= f.label :email %><br>
      </div>
      <%= f.email_field :email, required: true %>

      <br>
      <br>

      <div class="label">
        <%= f.label :message %><br>
      </div>
      <%= f.text_area :message, as: :text %>

      <div class="hidden">
        <div class="label">
          <%= f.label :nickname %><br>
        </div>
        <%= f.text_field :nickname, hint: 'leave this field blank' %>
      </div>

      <div class="new">
         <%= f.submit 'Send Message', class: "button" %>
      </div>


    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ollie on Rails</title>
  <link href='https://fonts.googleapis.com/css?family=Raleway:500' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Limelight' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
  <link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.css' rel='stylesheet'  type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header id="blog-main-header">
    <div class="eye-catch-text">
      <h1>Design.</h1>
      <h1>Development.</h1>
      <h1>Creativity.</h1>
    </div>
    <%= link_to "O | C", root_path %>
  </header>
  <div id="logout">
    <% if user_signed_in? %>
      <%= link_to destroy_user_session_path, method: :delete do %>
      <div class="logouth1">
        <h1>Sign Out</h1>
      </div>
      <% end %>
    <% end %>
  </div>

  <% if notice %>
    <p class="notice"><%= notice %></p>
  <% elsif alert %>
    <p class="alert"><%= alert %></p>
  <% end %>

  <%= yield %>

  <footer id="blog-main-footer">
    <div class="footer-container clearfix">
      <div class="copyright">Copyright &copy; 2016 Ollie on Rails</div>
    </div>
  </footer>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <% end %>

    <div class="label">
      <%= f.label :title %><br>
    </div>
    <%= f.text_field :title, placeholder: "Your post's title!" %>

    <br>
    <br>
    <div class="label">
      <%= f.label :content, "Write your article here" %><br>
    </div>
    <%= f.text_area :content, placeholder: "Your post's main content!" %>

    <br>
    <br>
    
    <div class="new">
      <%= f.submit %>
    </div>

<% end %>

app/views/posts/edit.html.erb
<div class="edit-post-container">
  <div class="edit-post-wrapper">
    <h1>Edit Post</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/posts/index.html.erb
<div id="articles-container">
  <div id="articles-wrapper">
    <h1 id="page-title">Stuff that I've written</h1>
    <% @posts.each do |post| %>
      <div class="article-post">
        <p class="date"><%= post.created_at.strftime('%A, %B %d') %></p>
        <h2><a href=""><%= link_to post.title, post %></a></h2>
        <hr class="post-sep">
      </div>
    <% end %>
  </div>

  <%= will_paginate @posts %>
</div>

app/views/posts/new.html.erb
<div class="new-post-container">
  <div class="new-post-wrapper">
    <h1>New Post</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/posts/show.html.erb
<div id="post-container">
  <div class="post-wrapper">
    <div class="post-title-container">
      <div class="post-title">
        <p class="date"><%= @post.created_at.strftime('%A, %B %d') %></p>
        <%= @post.title %><br>
      </div>
      <div class="edit">
        <% if user_signed_in? %>
          <%= link_to "Edit Article", edit_post_path(@post) %>
        <% end %>
      </div>
      <div class="delete">
        <% if user_signed_in? %>
          <%= link_to "Delete Article", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
        <% end %>
      </div>
    </div>
    <br>
    <br>

    <div class="post-content">
      <%= markdown @post.content %>
    </div>

    <div class="share-post">
      <h2>How about sharing '<%= @post.title %>' ?</h2>
      <!-- Twitter -->
      <a onclick="javascript:window.open('http://twitter.com/share?text=<%= @post.title %> by @olliedevdesign - &amp;url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');voide(0)">
        <i class="fa fa-twitter"></i>
      </a>
      <!-- Facebook -->
      <a onclick="javascript:window.open('http://facebook.com/sharer.php?u<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');voide(0)">
        <i class="fa fa-facebook"></i>
      </a>
      <!-- Google Plus -->
      <a onclick="javascript:window.open('https://plus.google.com/share?url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');voide(0)">
        <i class="fa fa-google-plus"></i>
      </a>
    </div>
  </div>
</div>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <% if @project.errors.any? %>
    <h2><%= pluralize(@project.errors.count, "error") %> prevented this project from saving</h2>
    <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <% end %>

    <div class="label">
      <%= f.label :title %><br>
    </div>
    <%= f.text_field :title, placeholder: "Your project's title!" %>

    <br>
    <br>

    <div class="label">
      <%= f.label :description %><br>
    </div>
    <%= f.text_area :description, placeholder: "Your project's main content!" %>

    <br>
    <br>

    <div class="label">
      <%= f.label :link %><br>
    </div>
    <%= f.text_field :link, placeholder: "Add a link to your project? Maybe?" %>

    <br>
    <br>

    <div class="new">
      <%= f.submit %>
    </div>

<% end %>

app/views/projects/edit.html.erb
<div class="new-project-container">
  <div class="new-project-wrapper">
    <h1>Edit Project</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/projects/index.html.erb
<div id="projects-container">
  <div id="projects-wrapper">
    <h1 id="page-title">Things that I have built</h1>
    <% @projects.each do |project| %>
      <div class="project-post">
        <p class="date"><%= project.created_at.strftime('%A, %B %d') %></p>
        <h2><a href=""><%= link_to project.title, project %></a></h2>
        <hr class="post-sep">
      </div>
    <% end %>
  </div>

app/views/projects/new.html.erb
<div class="new-project-container">
  <div class="new-project-wrapper">
    <h1>New Project</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/projects/show.html.erb
<div id="project-container">
  <div class="project-wrapper">
    <div class="project-title-container">
      <div class="project-title">
        <p class="date"><%= @project.created_at.strftime('%A, %B %d') %></p>
        <%= @project.title %><br>
      </div>
      <div class="edit">
        <% if user_signed_in? %>
          <%= link_to "Edit Project", edit_project_path(@project) %>
        <% end %>
      </div>
      <div class="delete">
        <% if user_signed_in? %>
          <%= link_to "Delete Project", project_path(@project), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
        <% end %>
      </div>
    </div>
    <br>
    <br>


    <div class="project-content">
      <%= markdown @project.description %>
    </div>
    <div class="project-link">
      <a href="<%= @project.link %>" class="project-button" target="_blank" >Visit '<%= @project.title %>'</a>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div id="main-wrapper">
  <div class="content-wrapper">
    <div class="articles-container">
      <div class="articles-wrapper">
        <% @posts.each do |post| %>
          <%= link_to post do %>
            <h1><%= post.title %></h1>
            <p class="date"><%= post.created_at.strftime("%A, %b %d") %></p>
          <% end %>
        <% end %>
      </div>
    </div>
    <%= link_to posts_path do %>
      <div class="post-more-container">
        <h1>More posts?</h1>
      </div>
    <% end %>
    <div class="projects-container">
      <div class="title-container">
        <h1>My recent projects</h1>
      </div>
      <div class="projects-wrapper">
        <% @projects.each do |project| %>
          <%= link_to project do %>
            <h1><%= project.title %></h1>
            <p class="date"><%= project.created_at.strftime("%A, %b %d") %></p>
          <% end %>
        <% end %>
      </div>
    </div>
    <%= link_to projects_path do %>
      <div class="project-more-container">
        <h1>More projects?</h1>
      </div>
    <% end %>
    <%= link_to new_contact_path do %>
      <div class="contact-container">
        <h1>Contact Me</h1>
      </div>
    <% end %>
  </div>
</div>